version: '3.1'

services:

  adminer:
    image: adminer:4.7
    restart: always
    ports:
    - 8080:8080

  dbPostgres:
    image: postgres:12.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: scrapy_tutorial